return {
	"tummetott/unimpaired.nvim",
	event = "VeryLazy",
	opts = {
		keymaps = {
			previous = false,
			next = false,
			first = false,
			last = false,
			bprevious = {
				mapping = "[b",
				description = "Jump to [count] previous buffer",
				dot_repeat = true,
			},
			bnext = {
				mapping = "]b",
				description = "Jump to [count] next buffer",
				dot_repeat = true,
			},
			bfirst = {
				mapping = "[B",
				description = "Jump to first buffer",
				dot_repeat = false,
			},
			blast = {
				mapping = "]B",
				description = "Jump to last buffer",
				dot_repeat = false,
			},
			lprevious = false,
			lnext = false,
			lfirst = {
				mapping = "[L",
				description = "Jump to first entry in loclist",
				dot_repeat = false,
			},
			llast = {
				mapping = "]L",
				description = "Jump to last entry in loclist",
				dot_repeat = false,
			},
			lpfile = {
				mapping = "[<c-l>",
				description = "Jump to last entry of [count] previous file in loclist",
				dot_repeat = true,
			},
			lnfile = {
				mapping = "]<c-l>",
				description = "Jump to first entry of [count] next file in loclist",
				dot_repeat = true,
			},
			cprevious = false,
			cnext = false,
			cfirst = {
				mapping = "[Q",
				description = "Jump to first entry in qflist",
				dot_repeat = false,
			},
			clast = {
				mapping = "]Q",
				description = "Jump to last entry in qflist",
				dot_repeat = false,
			},
			cpfile = {
				mapping = "[<c-q>",
				description = "Jump to last entry of [count] previous file in qflist",
				dot_repeat = true,
			},
			cnfile = {
				mapping = "]<c-q>",
				description = "Jump to first entry of [count] next file in qflist",
				dot_repeat = true,
			},
			tprevious = false,
			tnext = false,
			tfirst = false,
			tlast = false,
			ptprevious = false,
			ptnext = false,
			previous_file = false,
			next_file = false,
			blank_above = {
				mapping = "[<leader>",
				description = "Add [count] blank lines above",
				dot_repeat = true,
			},
			blank_below = {
				mapping = "]<leader>",
				description = "Add [count] blank lines below",
				dot_repeat = true,
			},
			exchange_above = {
				mapping = "[x",
				description = "Exchange line with [count] lines above",
				dot_repeat = true,
			},
			exchange_below = {
				mapping = "]x",
				description = "Exchange line with [count] lines below",
				dot_repeat = true,
			},
			exchange_section_above = {
				mapping = "[x",
				description = "Move section [count] lines up",
				dot_repeat = true,
			},
			exchange_section_below = {
				mapping = "]x",
				description = "Move section [count] lines down",
				dot_repeat = true,
			},
			enable_cursorline = false,
			disable_cursorline = false,
			toggle_cursorline = {
				mapping = "yoc",
				description = "Toggle cursorline",
				dot_repeat = true,
			},
			enable_diff = false,
			disable_diff = false,
			toggle_diff = false,
			enable_hlsearch = false,
			disable_hlsearch = false,
			toggle_hlsearch = {
				mapping = "yoh",
				description = "Toggle hlsearch",
				dot_repeat = true,
			},
			enable_ignorecase = false,
			disable_ignorecase = false,
			toggle_ignorecase = {
				mapping = "yoi",
				description = "Toggle ignorecase",
				dot_repeat = true,
			},
			enable_list = false,
			disable_list = false,
			toggle_list = {
				mapping = "yol",
				description = "Toggle invisible characters (listchars)",
				dot_repeat = true,
			},
			enable_number = false,
			disable_number = false,
			toggle_number = {
				mapping = "<leader>b",
				description = "Toggle line numbers",
				dot_repeat = true,
			},
			enable_relativenumber = false,
			disable_relativenumber = false,
			toggle_relativenumber = {
				mapping = "yor",
				description = "Toggle relative numbers",
				dot_repeat = true,
			},
			enable_spell = false,
			disable_spell = false,
			toggle_spell = {
				mapping = "<leader>p",
				description = "Toggle spell check",
				dot_repeat = true,
			},
			enable_background = false,
			disable_background = false,
			toggle_background = {
				mapping = "yob",
				description = "Toggle background",
				dot_repeat = true,
			},
			enable_colorcolumn = false,
			disable_colorcolumn = false,
			toggle_colorcolumn = {
				mapping = "yot",
				description = "Toggle colorcolumn",
				dot_repeat = true,
			},
			enable_cursorcolumn = false,
			disable_cursorcolumn = false,
			toggle_cursorcolumn = {
				mapping = "you",
				description = "Toggle cursorcolumn",
				dot_repeat = true,
			},
			enable_virtualedit = false,
			disable_virtualedit = false,
			toggle_virtualedit = {
				mapping = "yov",
				description = "Toggle virtualedit",
				dot_repeat = true,
			},
			enable_wrap = false,
			disable_wrap = false,
			toggle_wrap = {
				mapping = "<leader>a",
				description = "Toggle line wrapping",
				dot_repeat = true,
			},
			enable_cursorcross = false,
			disable_cursorcross = false,
			toggle_cursorcross = {
				mapping = "yox",
				description = "Toggle cursorcross",
				dot_repeat = true,
			},
		},
	},
}
